apiVersion: apps/v1
kind: Deployment
metadata:
  name: geth-bootnode-deployment
  labels:
    app: geth-bootnode
    app.kubernetes.io/name: geth-bootnode
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geth-bootnode
  template:
    metadata:
      labels:
        app: geth-bootnode
    spec:
      containers:
      - name: geth-bootnode
        image: 0x6e6869/ethereum-node:latest
        ports:
        - containerPort: 8545
        args:
          - "--nodekeyhex=b0ac22adcad37213c7c565810a50f1772291e7b0ce53fb73e7ec2a3c75bc13b5"
          - "--nodiscover"
          - "--ipcdisable"
          - "--networkid=1214"




