apiVersion: v1
kind: Service
metadata:
  name: geth-bootnode-service
spec:
  selector:
    app.kubernetes.io/name: geth-bootnode
  ports:
  - name: http-api
    protocol: TCP
    port: 8545
    targetPort: 8545
  - name: peer-to-peer
    protocol: TCP
    port: 30303
    targetPort: 30303

--- 
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app.kubernetes.io/name: node
  ports:
  - name: http-api
    protocol: TCP
    port: 8545
    targetPort: 8545
  - name: peer-to-peer
    protocol: TCP
    port: 30303
    targetPort: 30303