apiVersion: v1
kind: Service
metadata:
  name: geth-bootnode-service
spec:
  selector:
    app.kubernetes.io/name: geth-bootnode
  ports:
  - name: geth-bootnode-port
    protocol: TCP
    port: 8545
    targetPort: 8545
  - name: geth-bootnode-port
    protocol: TCP
    port: 30303
    targetPort: 30303